### ISSUE TITLE
s390x/ppc64le manifest is missing for perl:latest dockerhub image

### ISSUE THREAD

**Issue by Basavaraju-G** [Perl/docker-perl#145] opened 2023-10-04 08:35 UTC
latest perl image is not multi-arch. we are unable to run it on ppc64le and s390x arch. 

```
docker pull perl
```

Getting below error while pull it on s390x machine:
```
docker pull perl
Using default tag: latest
latest: Pulling from library/perl
no matching manifest for linux/s390x in the manifest list entries
```
but i was able to pull image with devel tag
```
docker pull perl:devel-bullseye
devel-bullseye: Pulling from library/perl
Digest: sha256:a2a90da5e4665b36514936299d7a283a69f28af43e6bbd3a542b08e5750d5b15
Status: Image is up to date for perl:devel-bullseye
docker.io/library/perl:devel-bullseye
```
However with tags image is supports s390x/ppc64le but perl:latest image is missing this archs. would you please build multi-arch for perl:latest image also.

<img width="1217" alt="Screenshot 2023-10-04 at 2 03 25 PM" src="https://github.com/Perl/docker-perl/assets/7733303/c07acb63-3312-4aee-b5f0-9c05ad176e22">

latest is missing additional archs.
<img width="1377" alt="Screenshot 2023-10-04 at 2 15 01 PM" src="https://github.com/Perl/docker-perl/assets/7733303/4ee5aae5-f316-4a9a-a40d-3d4b98c441e4">

**Comment by zakame** [comment] 2023-10-04 13:46
Hi @Basavaraju-G , thanks for the report! 🙏 

Yep, this seems like a regression caused by https://github.com/zakame/docker-library-official-images/commit/ee206638804862a2c8fd4b7fe6ca8de1c9a7fa86 and https://github.com/Perl/docker-perl/commit/dc1c61c6ef2654065dfc0260d61cb85b4d0676de - will post a fix 💪 

For the meantime, you can fetch `perl:5.38-bullseye` (and any other version built on Debian 11) for s390x/ppc64le/mips64le.

**Comment by zakame** [comment] 2023-10-04 14:24
Will keep this open until https://github.com/docker-library/official-images/pull/15475 is merged.

**Closed** 2023-10-05 03:58 UTC
