### ISSUE TITLE
cpanm no longer checks backpan

### ISSUE THREAD

**Issue by srchulo** [Perl/docker-perl#116] opened 2022-06-05 00:28 UTC
This change:

https://github.com/Perl/docker-perl/commit/6dc03932349674b283430f75d201c8bdcfffb402

Broke `cpanm` installs from backpan with this line:

```
ENV PERL_CPANM_OPT="--from https://www.cpan.org"
```

Causing commands like:

```
cpanm App::cpm@0.997002
```

To fail with:

```
Found App::cpm 0.997011 which doesn't satisfy == 0.997002.
```

Not sure if this was intentional or not?

**Comment by zakame** [comment] 2022-06-05 04:38
Hi @srchulo, yep, it is caused by #115 - there is discussion there to track this.

**Comment by zakame** [comment] 2022-06-05 05:25
Fix is merged but now need a new docker-library release - will post PR there shortly.

**Closed** 2022-06-05 05:25 UTC
